### ISSUE TITLE
OutOfMemory exception for the JobManager

### ISSUE THREAD

**Issue by debakkerb** [spotify/flink-on-k8s-operator#157]
Is there a way to tweak memory usage for the JobManager?  I've deployed the Flink operator on a GKE cluster and I was able to successfully launch the WordCount job.  However, when I launch a custom job, it almost immediately fails due to `java.lang.OutOfMemoryError: Java heap space`.

```
        at org.apache.flink.client.program.OptimizerPlanEnvironment.generateException(OptimizerPlanEnvironment.java:150)
        at org.apache.flink.client.program.OptimizerPlanEnvironment.getPipeline(OptimizerPlanEnvironment.java:90)
        at org.apache.flink.client.program.PackagedProgramUtils.getPipelineFromProgram(PackagedProgramUtils.java:108)
        at org.apache.flink.client.program.PackagedProgramUtils.createJobGraph(PackagedProgramUtils.java:58)
        at org.apache.flink.runtime.webmonitor.handlers.utils.JarHandlerUtils$JarHandlerContext.toJobGraph(JarHandlerUtils.java:128)
        at org.apache.flink.runtime.webmonitor.handlers.JarRunHandler.lambda$getJobGraphAsync$6(JarRunHandler.java:138)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

I'm deploying a custom container, which runs Tensorflow models.  I already tried setting the limits of the jobManager to "8Gi", but even then it still failed.  I had a look at the CRD for the JobManager, but there doesn't seem to set a parameter where you can tweak memory usage.  I also had a look at the parameters to run the job, but I can't find anything either.

**Comment by debakkerb** [comment]
When the JobManager is started, I can see this in the logs:

```
2021-11-30 08:47:07,063 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint         -  Starting StandaloneSessionClusterEntrypoint (Version: 1.10.3, Rev:2b8b670, Date:20.01.2021 @ 11:45:46 CST)
2021-11-30 08:47:07,063 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint         -  OS current user: flink
2021-11-30 08:47:07,063 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint         -  Current Hadoop/Kerberos user: <no hadoop dependency found>
2021-11-30 08:47:07,063 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint         -  JVM: OpenJDK 64-Bit Server VM - Oracle Corporation - 1.8/25.292-b10
2021-11-30 08:47:07,063 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint         -  Maximum heap size: 1820 MiBytes
2021-11-30 08:47:07,063 INFO  org.apache.flink.runtime.entrypoint.ClusterEntrypoint         -  JAVA_HOME: /usr/local/openjdk-8
```

That maximum heap size seems really small.

**Comment by regadas** [comment]
Hi @debakkerb!

Can you provide an example of your `FlinkCluster` resource? I suspect you are not setting the `flinkVersion` property.

**Comment by debakkerb** [comment]
Hey @regadas 

Apologies, I forgot to update the ticket.  I didn't fully realise that you could set the heap size in the `flinkProperties`-section in the YAML config:

```
flinkProperties:
  taskmanager.numberOfTaskSlots: "1"
  jobmanager.memory.heap.size: "4Gi"
```

Now I get a different error though, which is causing a lot of confusion on our end:

```
2021-12-03 10:54:50,752 INFO  org.apache.flink.api.java.ExecutionEnvironment                - The job has 0 registered types and 0 default Kryo serializers
2021-12-03 10:54:50,788 ERROR org.apache.flink.runtime.webmonitor.handlers.JarRunHandler    - Unhandled exception.
org.apache.flink.optimizer.CompilerException: Cannot currently handle nodes with more than 64 outputs.
        at org.apache.flink.optimizer.dag.OptimizerNode.addOutgoingConnection(OptimizerNode.java:348)
        at org.apache.flink.optimizer.dag.SingleInputNode.setInput(SingleInputNode.java:202)
        at org.apache.flink.optimizer.traversals.GraphCreatingVisitor.postVisit(GraphCreatingVisitor.java:272)
        at org.apache.flink.optimizer.traversals.GraphCreatingVisitor.postVisit(GraphCreatingVisitor.java:82)
```

I haven't spent a lot of time investigating, but the guys who wrote our code state that they are not using that many outputs.

**Comment by regadas** [comment]
Hi @debakkerb I think we can close this issue as it seems unrelated now. If if you feel it's still relevant please reopen.
