### ISSUE TITLE
nil pointer dereference on job update

### ISSUE THREAD

**Issue by Oliver-Sellwood** [spotify/flink-on-k8s-operator#160]
Hey,

I am getting the following log in the flink operator manager when trying to apply an updated manifest (changing the resource limits if that makes any difference)

I have tried with v0.3.0, v0.3.1, v0.2.2 and v0.2.1

The operator is able to create the cluster in the first place but any further changes to the manifest result in a crash and the cluster never updates.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x464 pc=0x143aad3]

goroutine 359 [running]:
github.com/spotify/flink-on-k8s-operator/controllers.(*FlinkJobSubmitter).getState(...)
	/workspace/controllers/flinkcluster_observer.go:109
github.com/spotify/flink-on-k8s-operator/controllers.(*ClusterStatusUpdater).deriveJobStatus(0x19ab110)
	/workspace/controllers/flinkcluster_updater.go:584 +0x653
github.com/spotify/flink-on-k8s-operator/controllers.(*ClusterStatusUpdater).deriveClusterStatus(_, _, _)
	/workspace/controllers/flinkcluster_updater.go:466 +0x16f7
github.com/spotify/flink-on-k8s-operator/controllers.(*ClusterStatusUpdater).updateStatusIfChanged(0xc001397908)
	/workspace/controllers/flinkcluster_updater.go:65 +0xb7
github.com/spotify/flink-on-k8s-operator/controllers.(*FlinkClusterHandler).reconcile(0xc001397c18, {0x17b0df1, 0x4}, {{{0xc0003e0a40, 0x25d8d20}, {0xc000048d20, 0x203000}}})
	/workspace/controllers/flinkcluster_controller.go:163 +0x3a5
github.com/spotify/flink-on-k8s-operator/controllers.(*FlinkClusterReconciler).Reconcile(0xc0007292c0, {0x19bddd8, 0xc0005dbd70}, {{{0xc0003e0a40, 0x5}, {0xc000048d20, 0x13}}})
	/workspace/controllers/flinkcluster_controller.go:84 +0x30d
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002fe820, {0x19bdd30, 0xc000320000}, {0x162cb60, 0xc000907bc0})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:298 +0x303
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0002fe820, {0x19bdd30, 0xc000320000})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:253 +0x205
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:214 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.6/pkg/internal/controller/controller.go:210 +0x354

```

**Comment by live-wire** [comment]
@Oliver-Sellwood Till we decide the expected behaviour for this use case, I'd recommend you create a new `FlinkCluster` object whenever you want to update the resource limits. (You could do that by just changing `metadata.name` and that would be applied as a new resource.)

**Comment by Oliver-Sellwood** [comment]
OK, thanks!!
