### ISSUE TITLE
Running into "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by borah-hemanga** [spotify/flink-on-k8s-operator#339]
I am trying to run the operator on K8s, and trying 'make deploy'. The pod comes up and starts running, but then I run into this:

`$ logs -f flink-operator-controller-manager-bc4ffd44f-ngzk9
W0321 22:59:05.794876       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0321 22:59:07.138118       1 request.go:665] Waited for 1.046424514s due to client-side throttling, not priority and fairness, request: GET:https://10.40.48.1:443/apis/certificates.k8s.io/v1beta1?timeout=32s
{"level":"info","ts":1647903548.542346,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":"127.0.0.1:8080"}
{"level":"info","ts":1647903548.543125,"logger":"controller-runtime.builder","msg":"Registering a mutating webhook","GVK":"flinkoperator.k8s.io/v1beta1, Kind=FlinkCluster","path":"/mutate-flinkoperator-k8s-io-v1beta1-flinkcluster"}
{"level":"info","ts":1647903548.5432432,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/mutate-flinkoperator-k8s-io-v1beta1-flinkcluster"}
{"level":"info","ts":1647903548.5433233,"logger":"controller-runtime.builder","msg":"Registering a validating webhook","GVK":"flinkoperator.k8s.io/v1beta1, Kind=FlinkCluster","path":"/validate-flinkoperator-k8s-io-v1beta1-flinkcluster"}
{"level":"info","ts":1647903548.5433788,"logger":"controller-runtime.webhook","msg":"Registering webhook","path":"/validate-flinkoperator-k8s-io-v1beta1-flinkcluster"}
{"level":"info","ts":1647903548.5434427,"logger":"setup","msg":"Starting manager"}
{"level":"info","ts":1647903548.5436523,"logger":"controller-runtime.webhook.webhooks","msg":"Starting webhook server"}
{"level":"info","ts":1647903548.543779,"msg":"Starting server","path":"/metrics","kind":"metrics","addr":"127.0.0.1:8080"}
I0321 22:59:08.544196       1 leaderelection.go:248] attempting to acquire leader lease flink-operator-system/flink-operator-lock...
{"level":"info","ts":1647903548.545192,"logger":"controller-runtime.certwatcher","msg":"Updated current TLS certificate"}
{"level":"info","ts":1647903548.5460224,"logger":"controller-runtime.webhook","msg":"Serving webhook server","host":"","port":9443}
{"level":"info","ts":1647903548.5462193,"logger":"controller-runtime.certwatcher","msg":"Starting certificate watcher"}
I0321 22:59:25.823492       1 leaderelection.go:258] successfully acquired lease flink-operator-system/flink-operator-lock
{"level":"info","ts":1647903565.8237221,"logger":"controller.flinkcluster","msg":"Starting EventSource","reconciler group":"flinkoperator.k8s.io","reconciler kind":"FlinkCluster","source":"kind source: *v1beta1.FlinkCluster"}
{"level":"info","ts":1647903565.823861,"logger":"controller.flinkcluster","msg":"Starting EventSource","reconciler group":"flinkoperator.k8s.io","reconciler kind":"FlinkCluster","source":"kind source: *v1.Deployment"}
{"level":"info","ts":1647903565.8238704,"logger":"controller.flinkcluster","msg":"Starting EventSource","reconciler group":"flinkoperator.k8s.io","reconciler kind":"FlinkCluster","source":"kind source: *v1.StatefulSet"}
{"level":"info","ts":1647903565.8238792,"logger":"controller.flinkcluster","msg":"Starting EventSource","reconciler group":"flinkoperator.k8s.io","reconciler kind":"FlinkCluster","source":"kind source: *v1.Service"}
{"level":"info","ts":1647903565.8238864,"logger":"controller.flinkcluster","msg":"Starting EventSource","reconciler group":"flinkoperator.k8s.io","reconciler kind":"FlinkCluster","source":"kind source: *v1.Job"}
{"level":"info","ts":1647903565.823892,"logger":"controller.flinkcluster","msg":"Starting Controller","reconciler group":"flinkoperator.k8s.io","reconciler kind":"FlinkCluster"}
{"level":"info","ts":1647903567.18347,"logger":"controller.flinkcluster","msg":"Starting workers","reconciler group":"flinkoperator.k8s.io","reconciler kind":"FlinkCluster","worker count":1}
{"level":"info","ts":1647903567.1836877,"logger":"controllers.FlinkCluster","msg":"============================================================","cluster":"flink-operator-system/flinkjobcluster-sample"}
{"level":"info","ts":1647903567.1837046,"logger":"controllers.FlinkCluster","msg":"---------- 1. Observe the current state ----------","cluster":"flink-operator-system/flinkjobcluster-sample"}
{"level":"info","ts":1647903567.1837897,"logger":"controllers.FlinkCluster","msg":"Observed cluster","cluster":"flink-operator-system/flinkjobcluster-sample","cluster":{"kind":"FlinkCluster","apiVersion":"flinkoperator.k8s.io/v1beta1","metadata":{"name":"flinkjobcluster-sample","namespace":"flink-operator-system","uid":"56274eda-eb66-450b-ba29-d8de1f5c8090","resourceVersion":"1347453462","generation":1,"creationTimestamp":"2022-03-21T21:32:04Z","annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"flinkoperator.k8s.io/v1beta1\",\"kind\":\"FlinkCluster\",\"metadata\":{\"annotations\":{},\"name\":\"flinkjobcluster-sample\",\"namespace\":\"flink-operator-system\"},\"spec\":{\"flinkProperties\":{\"taskmanager.numberOfTaskSlots\":\"1\"},\"image\":{\"name\":\"flink:1.8.2\"},\"job\":{\"args\":[\"--input\",\"./README.txt\"],\"className\":\"org.apache.flink.streaming.examples.wordcount.WordCount\",\"jarFile\":\"./examples/streaming/WordCount.jar\",\"parallelism\":2,\"restartPolicy\":\"Never\"},\"jobManager\":{\"accessScope\":\"Cluster\",\"ports\":{\"ui\":8081},\"resources\":{\"limits\":{\"cpu\":\"200m\",\"memory\":\"1024Mi\"}}},\"taskManager\":{\"replicas\":2,\"resources\":{\"limits\":{\"cpu\":\"200m\",\"memory\":\"1024Mi\"}}}}}\n"},"managedFields":[{"manager":"kubectl-client-side-apply","operation":"Update","apiVersion":"flinkoperator.k8s.io/v1beta1","time":"2022-03-21T21:32:04Z","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{".":{},"f:flinkProperties":{".":{},"f:taskmanager.numberOfTaskSlots":{}},"f:image":{".":{},"f:name":{}},"f:job":{".":{},"f:args":{},"f:className":{},"f:jarFile":{},"f:parallelism":{},"f:restartPolicy":{}},"f:jobManager":{".":{},"f:accessScope":{},"f:ports":{".":{},"f:ui":{}},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}}}},"f:taskManager":{".":{},"f:replicas":{},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}}}}}}},{"manager":"flink-operator","operation":"Update","apiVersion":"flinkoperator.k8s.io/v1beta1","time":"2022-03-21T21:32:57Z","fieldsType":"FieldsV1","fieldsV1":{"f:status":{".":{},"f:components":{".":{},"f:configMap":{".":{},"f:name":{},"f:state":{}},"f:job":{".":{},"f:id":{},"f:state":{}},"f:jobManagerService":{".":{},"f:name":{},"f:state":{}},"f:jobManagerStatefulSet":{".":{},"f:name":{},"f:state":{}},"f:taskManagerStatefulSet":{".":{},"f:name":{},"f:state":{}}},"f:currentRevision":{},"f:lastUpdateTime":{},"f:nextRevision":{},"f:state":{}}}}]},"spec":{"flinkVersion":"","image":{"name":"flink:1.8.2","pullPolicy":"Always"},"jobManager":{"replicas":1,"accessScope":"Cluster","ports":{"rpc":6123,"blob":6124,"query":6125,"ui":8081},"resources":{"limits":{"cpu":"200m","memory":"1Gi"}},"memoryOffHeapRatio":25,"memoryOffHeapMin":"600M"},"taskManager":{"replicas":2,"ports":{"data":6121,"rpc":6122,"query":6125},"resources":{"limits":{"cpu":"200m","memory":"1Gi"}},"memoryOffHeapRatio":25,"memoryOffHeapMin":"600M"},"job":{"jarFile":"./examples/streaming/WordCount.jar","className":"org.apache.flink.streaming.examples.wordcount.WordCount","args":["--input","./README.txt"],"allowNonRestoredState":false,"parallelism":2,"noLoggingToStdout":false,"restartPolicy":"Never","cleanupPolicy":{"afterJobSucceeds":"DeleteCluster","afterJobFails":"KeepCluster","afterJobCancelled":"DeleteCluster"},"resources":{}},"flinkProperties":{"taskmanager.numberOfTaskSlots":"1"},"recreateOnUpdate":true},"status":{"state":"Stopped","components":{"configMap":{"name":"flinkjobcluster-sample-configmap","state":"Deleted"},"jobManagerStatefulSet":{"name":"flinkjobcluster-sample-jobmanager","state":"Deleted"},"jobManagerService":{"name":"flinkjobcluster-sample-jobmanager","state":"Deleted"},"taskManagerStatefulSet":{"name":"flinkjobcluster-sample-taskmanager","state":"Deleted"},"job":{"id":"332bcd6b2f253498be3998ee7722012a","state":"Succeeded"}},"revision":{},"lastUpdateTime":"2022-03-21T21:33:12Z"}}}
{"level":"info","ts":1647903567.787995,"logger":"controllers.FlinkCluster","msg":"Observed controllerRevisions","cluster":"flink-operator-system/flinkjobcluster-sample","controllerRevisions":"[{name: flinkjobcluster-sample-d966866c9, revision: 1},]"}
{"level":"info","ts":1647903574.5911624,"logger":"controllers.FlinkCluster","msg":"Observed configMap","cluster":"flink-operator-system/flinkjobcluster-sample","state":"nil"}
{"level":"info","ts":1647903574.5914528,"logger":"controllers.FlinkCluster","msg":"Deployment not found","cluster":"flink-operator-system/flinkjobcluster-sample","component":"JobManager"}
{"level":"info","ts":1647903574.591488,"logger":"controllers.FlinkCluster","msg":"Observed JobManager StatefulSet","cluster":"flink-operator-system/flinkjobcluster-sample","state":"nil"}
{"level":"info","ts":1647903574.5915327,"logger":"controllers.FlinkCluster","msg":"Observed JobManager service","cluster":"flink-operator-system/flinkjobcluster-sample","state":"nil"}
{"level":"info","ts":1647903574.6919804,"logger":"controllers.FlinkCluster","msg":"Observed JobManager ingress","cluster":"flink-operator-system/flinkjobcluster-sample","state":"nil"}
{"level":"info","ts":1647903574.692173,"logger":"controllers.FlinkCluster","msg":"Deployment not found","cluster":"flink-operator-system/flinkjobcluster-sample","component":"TaskManager"}
{"level":"info","ts":1647903574.6922107,"logger":"controllers.FlinkCluster","msg":"Observed TaskManager StatefulSet","cluster":"flink-operator-system/flinkjobcluster-sample","state":"nil"}
{"level":"info","ts":1647903574.6922543,"logger":"controllers.FlinkCluster","msg":"Observed Flink job savepoint status","cluster":"flink-operator-system/flinkjobcluster-sample","status":null}
{"level":"info","ts":1647903574.793849,"logger":"controllers.FlinkCluster","msg":"Observed persistent volume claim list","cluster":"flink-operator-system/flinkjobcluster-sample","state":{"metadata":{},"items":[]}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14667a3]

goroutine 460 [running]:
github.com/spotify/flink-on-k8s-operator/controllers/flinkcluster.(*ClusterStateObserver).observeJob(0xc000d25738?, 0xc0003a33b0?)
	/workspace/controllers/flinkcluster/flinkcluster_observer.go:274 +0x63
github.com/spotify/flink-on-k8s-operator/controllers/flinkcluster.(*ClusterStateObserver).observe(0xc000d25738, 0xc000d25b68)
	/workspace/controllers/flinkcluster/flinkcluster_observer.go:252 +0xefd
github.com/spotify/flink-on-k8s-operator/controllers/flinkcluster.(*FlinkClusterHandler).reconcile(0xc000d25af0, {0x1812a14?, 0x2?}, {{{0xc00056b098?, 0x40a1cd?}, {0xc00056b080?, 0x7fc6d33555b8?}}})
	/workspace/controllers/flinkcluster/flinkcluster_controller.go:144 +0x2b8
github.com/spotify/flink-on-k8s-operator/controllers/flinkcluster.(*FlinkClusterReconciler).Reconcile(0xc0006fad00, {0x1a46230, 0xc0019063c0}, {{{0xc00056b098, 0x15}, {0xc00056b080, 0x16}}})
	/workspace/controllers/flinkcluster/flinkcluster_controller.go:85 +0x37b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00080cd10, {0x1a46230, 0xc001906300}, {{{0xc00056b098?, 0x17495a0?}, {0xc00056b080?, 0x4041f4?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:114 +0x27e
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00080cd10, {0x1a46188, 0xc0006fa140}, {0x167c460?, 0xc000908000?})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:311 +0x349
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00080cd10, {0x1a46188, 0xc0006fa140})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.1/pkg/internal/controller/controller.go:223 +0x31c`

Any ideas, what could be happening?

**Comment by borah-hemanga** [comment]
I deleted the entire namespace and retried, and it worked. Perhaps some configuration went wrong. :/
